// GENERATED by tools/build_shop.py from tools/shop-products.json -- do not edit by hand.
export default {
  "slippers": {
    "name": "Foldable Travel Slippers",
    "price": 38500,
    "variants": [
      [
        {
          "value": "36-37"
        },
        {
          "value": "38-39"
        },
        {
          "value": "40-41"
        },
        {
          "value": "42-43"
        }
      ]
    ]
  },
  "sweatpads": {
    "name": "Underarm Sweat Pads (10pcs)",
    "price": 35000,
    "variants": []
  },
  "earmuffs": {
    "name": "Foldable Cold Protection Earmuffs",
    "price": 85000,
    "variants": [
      [
        {
          "value": "Black"
        },
        {
          "value": "Brown"
        },
        {
          "value": "Pink"
        },
        {
          "value": "Beige"
        },
        {
          "value": "White"
        },
        {
          "value": "Grey"
        }
      ]
    ]
  },
  "insoles": {
    "name": "Forefoot Insoles Shoe Protector (pair)",
    "price": 35000,
    "variants": []
  },
  "packing-organizers": {
    "name": "Luggage Travel Organisers with Toiletry Case (8pcs)",
    "price": 105000,
    "variants": []
  },
  "toiletry-bag": {
    "name": "Hanging Large-Capacity Toiletry Bag",
    "price": 85000,
    "variants": []
  },
  "neck-pillow": {
    "name": "Inflatable Travel Neck Pillow",
    "price": 85000,
    "variants": []
  },
  "suitcase-cover": {
    "name": "Suitcase Cover",
    "price": 45000,
    "variants": [
      [
        {
          "value": "24",
          "price": 45000
        },
        {
          "value": "26",
          "price": 55000
        },
        {
          "value": "28",
          "price": 65000
        },
        {
          "value": "30",
          "price": 75000
        }
      ]
    ]
  },
  "shoe-covers": {
    "name": "Thickened Unisex Silicone Shoe Covers",
    "price": 65000,
    "variants": [
      [
        {
          "value": "Small"
        },
        {
          "value": "Medium"
        },
        {
          "value": "Large"
        }
      ],
      [
        {
          "value": "White"
        },
        {
          "value": "Black"
        },
        {
          "value": "Grey"
        },
        {
          "value": "Blue"
        }
      ]
    ]
  },
  "beach-tote": {
    "name": "Large-Capacity Beach & Swim Tote with Zip",
    "price": 85000,
    "variants": [
      [
        {
          "value": "Blue"
        },
        {
          "value": "Green"
        }
      ]
    ]
  },
  "short-stay-bags": {
    "name": "Short-Stay Fashion Bags (set)",
    "price": 205000,
    "variants": []
  },
  "soap-dish-case": {
    "name": "Travel Soap Dish Case",
    "price": 45000,
    "variants": []
  },
  "acrylic-soap-holder": {
    "name": "Acrylic Travel Soap Holder",
    "price": 55000,
    "variants": []
  },
  "vanity-mirror": {
    "name": "Rechargeable LED Travel Tablet Vanity Mirror",
    "price": 105000,
    "variants": []
  },
  "hair-bonnet": {
    "name": "Large Hair Bonnet",
    "price": 45000,
    "variants": []
  },
  "back-scrubber": {
    "name": "Back Scrubber with Handle",
    "price": 55000,
    "variants": []
  },
  "oral-irrigator": {
    "name": "Rechargeable Portable Oral Irrigator (4 nozzles)",
    "price": 95000,
    "variants": []
  },
  "face-lifter": {
    "name": "Face Shaping Mask / Face Lifter",
    "price": 65000,
    "variants": []
  },
  "anti-snoring-clip": {
    "name": "Anti-Snoring Aid Clip",
    "price": 85000,
    "variants": []
  },
  "neck-massager": {
    "name": "Electric Neck Massager",
    "price": 108000,
    "variants": []
  },
  "hot-water-bottle": {
    "name": "2L Hot Water Bottle",
    "price": 85000,
    "variants": []
  },
  "camp-chair": {
    "name": "Foldable Camp Chair",
    "price": 205000,
    "variants": []
  },
  "outdoor-chair": {
    "name": "Foldable Outdoor Chair with Wooden Armrests",
    "price": 170000,
    "variants": [
      [
        {
          "value": "Khaki"
        },
        {
          "value": "Black"
        }
      ]
    ]
  },
  "whisky-bottle": {
    "name": "Women's Stainless Double-Wall Whisky Bottle",
    "price": 65000,
    "variants": []
  },
  "wine-set": {
    "name": "Electric Wine Set",
    "price": 105000,
    "variants": []
  },
  "mesh-bags": {
    "name": "Washing Machine Mesh Net Bags (7pcs)",
    "price": 85000,
    "variants": []
  },
  "ironing-mat": {
    "name": "Foldable Ironing Mat",
    "price": 85000,
    "variants": []
  },
  "lint-remover": {
    "name": "Rechargeable Lint Remover",
    "price": 85000,
    "variants": []
  },
  "sewing-machine": {
    "name": "Portable Handheld Sewing Machine",
    "price": 75000,
    "variants": []
  },
  "budget-planner": {
    "name": "Binder Budget Planner",
    "price": 75000,
    "variants": [
      [
        {
          "value": "Black"
        },
        {
          "value": "Brown"
        }
      ]
    ]
  },
  "mobile-dustbins": {
    "name": "Aesthetic Mobile Dustbins",
    "price": 205000,
    "variants": []
  },
  "epilator": {
    "name": "Rechargeable Nano Glass 2-in-1 Epilator",
    "price": 65000,
    "variants": []
  },
  "neck-fan": {
    "name": "Gold Hanging Neck Fan",
    "price": 105000,
    "variants": []
  }
};
