"""Build the shop from tools/shop-products.json.

Regenerates:
  - the product grid inside shop.html (between the PRODUCTS markers)
  - one page per product: shop-<slug>.html
  - the shop-*.html entries in sitemap.xml

Run from anywhere:  python tools/build_shop.py
Photos live in assets/photos/shop/ and videos in assets/videos/shop/,
listed per product in the JSON (first photo is the main one).
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

PHOTO_DIR = 'assets/photos/shop/'
VIDEO_DIR = 'assets/videos/shop/'
PLACEHOLDER_IMAGE = 'assets/favicon.svg'   # cart thumbnail for items without a photo
SITE = 'https://elevertravel.com/'
START = '<!-- PRODUCTS:START (generated by tools/build_shop.py from tools/shop-products.json -- edit the JSON, not this block) -->'
END = '<!-- PRODUCTS:END -->'


def read(path):
    with open(path, encoding='utf-8', newline='') as f:
        return f.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(text)


def e(text):
    return html.escape(str(text), quote=True)


def ugx(n):
    return f'UGX {n:,}'


def page_url(p):
    return f'shop-{p["slug"]}.html'


def full_name(p):
    return p['name'] + (f' ({p["qtytag"]})' if p.get('qtytag') else '')


def name_html(p):
    tag = f' <span class="shop-card-qtytag">({e(p["qtytag"])})</span>' if p.get('qtytag') else ''
    return e(p['name']) + tag


def option(o):
    return o if isinstance(o, dict) else {'value': o, 'label': o}


def price_html(p, extra=''):
    was = f' <s class="shop-price-was">{ugx(p["was"])}</s>' if p.get('was') else ''
    return f'<div class="shop-price{extra}">{ugx(p["price"])}{was}</div>'


def variants_html(p, indent, prefix):
    out = []
    for v in p.get('variants', []):
        vid = f'{prefix}-{p["id"]}-{v["label"].lower()}'
        opts = []
        for o in map(option, v['options']):
            price = f' data-price="{o["price"]}"' if 'price' in o else ''
            opts.append(f'{indent}    <option value="{e(o["value"])}"{price}>{e(o["label"])}</option>')
        onchange = ' onchange="updateVariantPrice(this)"' if any('price' in option(o) for o in v['options']) else ''
        out.append(
            f'{indent}<div class="form-group">\n'
            f'{indent}  <label for="{vid}">{e(v["label"])}</label>\n'
            f'{indent}  <select id="{vid}" class="shop-variant" data-label="{e(v["label"])}"{onchange}>\n'
            + '\n'.join(opts) + '\n'
            f'{indent}  </select>\n'
            f'{indent}</div>')
    return '\n'.join(out)


QTY = ('<div class="qty-stepper qty-stepper-input">\n'
       '{i}  <button type="button" onclick="stepQty(this,-1)" aria-label="Decrease quantity">−</button>\n'
       '{i}  <input type="number" class="qty-input" value="1" min="1" aria-label="Quantity">\n'
       '{i}  <button type="button" onclick="stepQty(this,1)" aria-label="Increase quantity">+</button>\n'
       '{i}</div>')


def data_attrs(p):
    image = PHOTO_DIR + p['photos'][0] if p.get('photos') else PLACEHOLDER_IMAGE
    return (f'data-id="{e(p["id"])}" data-name="{e(full_name(p))}" '
            f'data-price="{p["price"]}" data-image="{e(image)}"')


def card(p):
    """Compact grid card: photo, name, price -- the whole card links to the
    product page, where the details, options and Add to Cart live."""
    url = page_url(p)
    badge = f'<span class="shop-badge">{e(p["badge"])}</span>' if p.get('badge') else ''
    if p.get('photos'):
        image = (f'<div class="shop-card-image" style="background-image: url(\'{PHOTO_DIR}{p["photos"][0]}\');">'
                 f'{badge}</div>')
    else:
        image = f'<div class="shop-card-image shop-photo-pending">{badge}<span>Photo coming soon</span></div>'
    sale = ''
    if p.get('was'):
        off = round((p['was'] - p['price']) * 100 / p['was'])
        sale = (f'\n        <div class="shop-card-sale"><s>{ugx(p["was"])}</s>'
                f'<span class="shop-discount">-{off}%</span></div>')
    return f'''    <!-- Product: {e(full_name(p))} -->
    <a class="shop-card" href="{url}" aria-label="{e(full_name(p))}, {ugx(p["price"])}">
      {image}
      <div class="shop-card-body">
        <h3 class="shop-card-name">{name_html(p)}</h3>
        <div class="shop-price">{ugx(p["price"])}</div>{sale}
      </div>
    </a>'''


def product_main(p):
    photos = [PHOTO_DIR + x for x in p.get('photos', [])]
    badge = f'<span class="shop-badge">{e(p["badge"])}</span>' if p.get('badge') else ''
    if photos:
        main = (f'<div class="product-main-image" id="productMainImage" style="background-image: url(\'{photos[0]}\');" '
                f'role="img" aria-label="{e(p["alt"])}">{badge}</div>')
    else:
        main = (f'<div class="product-main-image shop-photo-pending" id="productMainImage" role="img" '
                f'aria-label="Photo coming soon">{badge}<span>Photo coming soon</span></div>')
    thumbs = ''
    if len(photos) > 1:
        thumbs = '\n      <div class="product-thumbs">\n' + '\n'.join(
            f'        <button type="button" class="product-thumb{" active" if i == 0 else ""}" onclick="showProductPhoto(this)" '
            f'data-src="{src}" aria-label="Show photo {i + 1} of {len(photos)}"><img src="{src}" alt="" loading="lazy"></button>'
            for i, src in enumerate(photos)) + '\n      </div>'
    videos = ''
    if p.get('videos'):
        poster = f' poster="{photos[0]}"' if photos else ''
        videos = ('\n      <div class="product-videos">\n        <div class="blog-quick-facts-label">See it in use</div>\n' + '\n'.join(
            f'        <video src="{VIDEO_DIR}{v}" controls playsinline preload="none"{poster}></video>' for v in p['videos'])
            + '\n      </div>')
    note = f'\n      <div class="shop-card-note">{e(p["note"])}</div>' if p.get('note') else ''
    details = ''
    if p.get('details'):
        details = '\n        <ul>\n' + '\n'.join(f'          <li>{e(d)}</li>' for d in p['details']) + '\n        </ul>\n      '
    variants = variants_html(p, '      ', 'product')
    variants = '\n' + variants if variants else ''
    return f'''
<!-- ============================================
   PRODUCT PAGE: {e(full_name(p))}
   Generated by tools/build_shop.py from tools/shop-products.json --
   edit the JSON and re-run the script rather than this file.
   ============================================ -->
<section class="product-page">
  <div class="product-crumbs" role="navigation" aria-label="Breadcrumb"><a href="shop.html">Shop</a><span aria-hidden="true">/</span><span>{e(full_name(p))}</span></div>
  <div class="product-layout" {data_attrs(p)}>
    <div class="product-gallery">
      {main}{thumbs}{videos}
    </div>
    <div class="product-info">
      <div class="section-eyebrow">Travel Essentials</div>
      <h1 class="product-name">{name_html(p)}</h1>
      {price_html(p, ' product-price')}{note}
      <p class="product-desc">{e(p["summary"])}</p>
      <div class="product-details">{details}</div>{variants}
      <div class="product-buy">
        {QTY.format(i="        ")}
        <button class="btn-outline shop-add-btn" type="button" onclick="addToCart(this)">Add to Cart</button>
      </div>
      <a href="shop.html#shopCart" class="product-cart-link">View cart (<span class="cart-count">0</span>)</a>
    </div>
  </div>
  <p class="blog-more-link"><a href="shop.html">← Back to the shop</a></p>
</section>
'''


def main():
    products = json.loads(read('tools/shop-products.json'))
    for p in products:
        for ph in p.get('photos', []):
            assert os.path.exists(PHOTO_DIR + ph), f'missing photo {ph}'
        for v in p.get('videos', []):
            assert os.path.exists(VIDEO_DIR + v), f'missing video {v}'

    shop = read('shop.html')
    nl = '\r\n' if '\r\n' in shop else '\n'
    grid = '\n\n'.join(card(p) for p in products)
    block = f'{START}\n\n{grid}\n\n    {END}'.replace('\n', nl)
    if START in shop:
        shop = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda m: block, shop, flags=re.S)
    else:  # first run: replace the hand-written cards inside .shop-grid
        shop, n = re.subn(r'(<div class="shop-grid">\r?\n).*?(\r?\n  </div>\r?\n</section>)',
                          lambda m: m.group(1) + nl + '    ' + block + m.group(2), shop, count=1, flags=re.S)
        assert n == 1, 'could not find .shop-grid in shop.html'
    write('shop.html', shop)

    # product pages reuse shop.html's head, nav and footer (minus the payment widget)
    head, rest = shop.split('<main id="pageContent">', 1)
    tail = rest.split('</main>', 1)[1]
    tail = re.sub(r'<!-- Payment checkout widget.*?</script>\s*', '', tail, flags=re.S)
    for p in products:
        url = page_url(p)
        image = SITE + PHOTO_DIR + p['photos'][0] if p.get('photos') else SITE + 'assets/photos/large/blog-cover.jpg'
        title = f'{full_name(p)} | Elever Travel Shop'
        h = re.sub(r'<title>.*?</title>', lambda m: f'<title>{e(title)}</title>', head)
        h = re.sub(r'(<meta property="og:title" content=")[^"]*', lambda m: m.group(1) + e(title), h)
        for k in ('name="description"', 'property="og:description"'):
            h = re.sub(r'(<meta ' + k + r' content=")[^"]*', lambda m: m.group(1) + e(p['summary']), h)
        h = h.replace(SITE + 'shop.html', SITE + url)
        for k in ('og:image" content="', 'twitter:image" content="'):
            h = re.sub(re.escape(k) + r'[^"]*', lambda m: k + image, h)
        h = re.sub(r'(og:image:alt" content=")[^"]*', lambda m: m.group(1) + e(p['alt']), h)
        write(url, h + '<main id="pageContent">' + product_main(p).replace('\n', nl) + nl + '</main>' + tail)

    sm = read('sitemap.xml')
    snl = '\r\n' if '\r\n' in sm else '\n'
    sm = re.sub(r'\s*<url>\s*<loc>' + re.escape(SITE) + r'shop-[^<]*</loc>.*?</url>', '', sm, flags=re.S)
    entries = ''.join(f'  <url>{snl}    <loc>{SITE}{page_url(p)}</loc>{snl}    <changefreq>weekly</changefreq>{snl}'
                      f'    <priority>0.6</priority>{snl}  </url>{snl}' for p in products)
    sm = sm.replace('</urlset>', entries + '</urlset>').replace(f'</url>  <url>', f'</url>{snl}  <url>')
    write('sitemap.xml', sm)
    print(f'Built {len(products)} products.')


if __name__ == '__main__':
    main()
